# Generated by Django 3.0.6 on 2020-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20, verbose_name='sender name')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
            ],
        ),
    ]
